dist: trusty
sudo: false

language: ruby
cache: bundler

rvm:
  - 2.6
  - 2.7

gemfile:
  - gemfiles/activerecord_6.1.gemfile

script: bundle exec rake spec

addons:
  postgresql: "9.3"

before_install: gem update bundler
bundler_args: --jobs 3
install: bundle install --jobs 3

before_script:
  - psql -c 'create database "switchman_test";' -U postgres
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - bundle exec rake db:migrate
